spring.application.name=watch
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=sample;encrypt=true;trustServerCertificate=true
spring.datasource.username=root
spring.datasource.password=pass
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

server.port=1122
